using YamlDotNet.Serialization;

namespace MinuteOS.Build;

/// <summary>
/// Records the commit each mutable dependency ref (branch/tag) resolved to -
/// written by <c>minuteos restore</c>, read by builds so they stay offline and
/// deterministic between restores. Commit it for reproducible team builds;
/// re-running <c>restore</c> moves it to the current ref target.
/// </summary>
public sealed class DependencyLock
{
    public const string FileName = "minuteos.lock";

    private readonly string _path;
    private readonly Dictionary<string, string> _resolved;

    private DependencyLock(string path, Dictionary<string, string> resolved)
    {
        _path = path;
        _resolved = resolved;
    }

    public static DependencyLock Load(string projectRoot)
    {
        var path = System.IO.Path.Combine(projectRoot, FileName);
        Dictionary<string, string>? resolved = null;
        if (File.Exists(path))
        {
            try
            {
                resolved = new StaticDeserializerBuilder(new YamlContext())
                    .WithTypeConverter(StringMapConverter.Instance).Build()
                    .Deserialize<Dictionary<string, string>>(File.ReadAllText(path));
            }
            catch { /* corrupt lock - restore rewrites it */ }
        }
        return new DependencyLock(path, resolved ?? []);
    }

    /// <summary>The locked commit for a dependency, or null when never resolved.</summary>
    public string? Get(string name) => _resolved.GetValueOrDefault(name);

    public bool Dirty { get; private set; }

    public void Set(string name, string commit)
    {
        if (_resolved.GetValueOrDefault(name) == commit)
            return;
        _resolved[name] = commit;
        Dirty = true;
    }

    public void Save()
    {
        if (!Dirty)
            return;
        var yaml = new StaticSerializerBuilder(new YamlContext())
            .WithTypeConverter(StringMapConverter.Instance).Build().Serialize(_resolved);
        File.WriteAllText(_path,
            "# Generated by 'minuteos restore' - resolved dependency commits.\n" + yaml);
        Dirty = false;
    }
}
