using System.Text.RegularExpressions;
using MinuteOS.Cli.Build;
using triaxis.CommandLine;

namespace MinuteOS.Cli.Commands;

[Command("migrate", Description = "Convert legacy Include.mk files to component.yaml/target.yaml")]
public partial class MigrateCommand : LoggingCommand
{
    [Option("--path", "-p", Description = "Directory to migrate (a project or lib root; default: current directory)")]
    public string Directory { get; set; } = "";

    [Option("--dry-run", "-n", Description = "Show what would be written without changing anything")]
    public bool DryRun { get; set; }

    [Option("--force", "-f", Description = "Overwrite existing component.yaml/target.yaml")]
    public bool Force { get; set; }

    [Option("--delete-make", Description = "Delete each Include.mk that migrated with nothing left unhandled")]
    public bool DeleteMake { get; set; }

    public Task<int> ExecuteAsync(CancellationToken cancellationToken)
    {
        var root = Path.GetFullPath(Directory == "" ? System.IO.Directory.GetCurrentDirectory() : Directory);

        // Collect targets/ roots: directly under root, and under any lib* sibling.
        var targetRoots = new List<string>();
        foreach (var baseDir in new[] { root }.Concat(System.IO.Directory.Exists(root)
            ? System.IO.Directory.GetDirectories(root, "lib*") : []))
        {
            var t = Path.Combine(baseDir, "targets");
            if (System.IO.Directory.Exists(t))
                targetRoots.Add(t);
        }

        if (targetRoots.Count == 0)
        {
            Logger.LogError("No targets/ directory found under {Root}.", root);
            return Task.FromResult(1);
        }

        int written = 0, skipped = 0, manual = 0, deleted = 0;

        foreach (var targetRoot in targetRoots)
        {
            foreach (var mk in System.IO.Directory.EnumerateFiles(targetRoot, MakeImport.FileName, SearchOption.AllDirectories))
            {
                // Delete this Include.mk if requested and nothing was left unhandled.
                void DeleteIfClean(IReadOnlyList<string> leftover)
                {
                    if (DeleteMake && !DryRun && leftover.Count == 0)
                    {
                        File.Delete(mk);
                        deleted++;
                        Logger.LogInformation("DELETE  {File}", Rel(root, mk));
                    }
                }

                var dir = Path.GetDirectoryName(mk)!;
                var rel = Path.GetRelativePath(targetRoot, dir).Replace('\\', '/');
                var parts = rel.Split('/');
                var content = File.ReadAllText(mk);

                // One path segment under targets/ => a target; deeper => a component.
                var isTarget = parts.Length == 1;
                var yamlName = isTarget ? TargetMeta.FileName : ComponentMeta.FileName;
                var yamlPath = Path.Combine(dir, yamlName);

                string? yaml;
                if (isTarget)
                    yaml = MakeImport.LoadTarget(dir, parts[0])?.ToYaml();
                else
                    yaml = MakeImport.LoadComponent(dir, string.Join('/', parts.Skip(1)))?.ToYaml();

                var leftover = NonDeclarativeLines(content);

                if (yaml == null)
                {
                    // Nothing declarative to migrate.
                    if (leftover.Count > 0)
                    {
                        manual++;
                        Logger.LogWarning("MANUAL  {File} - non-declarative Make, needs build steps:", Rel(root, mk));
                        foreach (var l in leftover.Take(4))
                            Logger.LogWarning("            {Line}", l);
                        HintRecursiveMake(leftover);
                    }
                    DeleteIfClean(leftover);
                    continue;
                }

                if (!Force && File.Exists(yamlPath))
                {
                    skipped++;
                    Logger.LogInformation("SKIP    {File} (exists; use --force)", Rel(root, yamlPath));
                    DeleteIfClean(leftover);
                    continue;
                }

                if (DryRun)
                {
                    Logger.LogInformation("WOULD WRITE {File}:\n{Yaml}", Rel(root, yamlPath), Indent(yaml));
                }
                else
                {
                    File.WriteAllText(yamlPath,
                        "# Generated by 'minuteos migrate' from Include.mk. Review and commit.\n" + yaml);
                    Logger.LogInformation("WRITE   {File}", Rel(root, yamlPath));
                }
                written++;

                // A target/component file may also contain custom rules the YAML
                // can't express yet (objcopy outputs, DFU, ...). Flag those.
                if (leftover.Count > 0)
                {
                    manual++;
                    Logger.LogWarning("            ^ also has non-declarative Make (needs steps): {Lines}",
                        string.Join(" | ", leftover.Take(3)));
                    HintRecursiveMake(leftover);
                }
                DeleteIfClean(leftover);
            }
        }

        Logger.LogInformation("");
        Logger.LogInformation(
            "Migrated {Written} file(s), skipped {Skipped}, deleted {Deleted} Include.mk, {Manual} needing manual attention.{Dry}",
            written, skipped, deleted, manual, DryRun ? " (dry run - nothing written)" : "");
        return Task.FromResult(0);
    }

    /// <summary>
    /// Returns substantive Make lines the importer does not understand: rule
    /// targets, conditionals, includes, recipes - i.e. anything beyond the simple
    /// VAR =/+= assignments and comments.
    /// </summary>
    private static List<string> NonDeclarativeLines(string content)
    {
        var result = new List<string>();
        foreach (var raw in content.Split('\n'))
        {
            var line = raw.TrimEnd();
            var trimmed = line.TrimStart();
            if (trimmed.Length == 0 || trimmed.StartsWith('#'))
                continue;
            if (AssignmentRegex().IsMatch(trimmed) || trimmed.StartsWith(".PHONY"))
                continue;
            // objcopy rules/recipes/aliases are imported as shell steps.
            if (trimmed.Contains("$(OBJCOPY)")
                || ObjcopyRuleRegex().IsMatch(trimmed)
                || ObjcopyAliasRegex().IsMatch(trimmed))
                continue;
            // `run` targets are covered by `minuteos run`.
            if (RunTargetRegex().IsMatch(trimmed)
                || trimmed.Contains("$(TEST_RUN)")
                || RunRecipeRegex().IsMatch(trimmed))
                continue;
            result.Add(line.Trim());
        }
        return result;
    }

    /// <summary>
    /// Recognizes the recursive-<c>$(MAKE)</c> bootloader pattern (a nested build
    /// embedded as a blob) and points to its declarative replacement.
    /// </summary>
    private void HintRecursiveMake(IReadOnlyList<string> leftover)
    {
        if (!leftover.Any(l => l.Contains("$(MAKE)")))
            return;
        Logger.LogWarning(
            "            HINT: this is a recursive sub-build (e.g. a bootloader embedded as a blob).");
        Logger.LogWarning(
            "            Replace it with a 'sub-build' step referencing a sub-configuration, e.g.:");
        Logger.LogWarning(
            "              steps: [{{ name: sub-build, config: {{ configuration: bootldr, blob-section: .binboot }} }}]");
        Logger.LogWarning(
            "            plus a 'bootldr' configuration (its own target/components/source-dir/ld-script).");
    }

    private static string Rel(string root, string path) => Path.GetRelativePath(root, path);

    private static string Indent(string s) =>
        string.Join('\n', s.TrimEnd().Split('\n').Select(l => "    " + l));

    [GeneratedRegex(@"^\w[\w]*\s*[?:+]?=")]
    private static partial Regex AssignmentRegex();

    [GeneratedRegex(@"^\$\(OUTPUT\)\.\w+\s*:")]
    private static partial Regex ObjcopyRuleRegex();

    [GeneratedRegex(@"^(binary|ihex|srec)\s*:")]
    private static partial Regex ObjcopyAliasRegex();

    [GeneratedRegex(@"^run\s*:")]
    private static partial Regex RunTargetRegex();

    // A recipe that just launches the built binary, e.g. `@$(OUTPUT).elf`.
    [GeneratedRegex(@"^@?\$\(OUTPUT\)\.\w+\s*$")]
    private static partial Regex RunRecipeRegex();
}
